name: Mirror Models

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [0,1,2,3,4]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install huggingface_hub gitpython

      - name: Mirror Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_ORG: ${{ secrets.HF_ORG }}
        run: |
          python mirror.py ${{ matrix.model }}
